# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cocktail' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya'
  pod 'Moya-ObjectMapper'
  pod 'SDWebImage'
pod 'GoogleMaps'
pod 'lottie-ios'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'
pod 'FirebaseDatabase'
pod 'Firebase/Firestore'
pod 'FirebaseStorage'

end
